### ISSUE TITLE
.bind() jquery calls are being deprecated

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/storefront-footer-bar#16]
The .bind calls within the plugin js are being deprecated

https://jquery.com/upgrade-guide/3.0/#deprecated-bind-and-delegate

**Comment by yeremi** [comment]
Hello @jconroy ,

- jQuery documentation said `.bind()` is deprecated from 3.0 https://api.jquery.com/bind/ 
- Currently, the jQuery version used by WP 5.8 (latest version today) is v3.6.0.
- jQuery v3.6.0 has `.bind()` on its library and calls for `.on()`. 

```js
// https://code.jquery.com/jquery-3.6.0.js
jQuery.fn.extend( {
	bind: function( types, data, fn ) {
            return this.on( types, null, data, fn );
	},
	// ...
});

// http://code.jquery.com/jquery-1.3.js
jQuery.fn.extend({
	bind: function( type, data, fn ) {
            return type == "unload" ? this.one(type, data, fn) : this.each(function(){
                jQuery.event.add( this, type, fn || data, fn && data );
	    });
	},
        // ...
});
```

- jQuery recommend to use `.on()` instead of `.bind()`.

---

**Consideration 1:**

I realized that the `.bind()` method in this plugin is not the same as jQuery `.bind()` due to its syntax.

https://www.javascripttutorial.net/javascript-bind/
https://api.jquery.com/bind/
```js
// Javascript
fn.bind(thisArg[, arg1[, arg2[, ...]]])

// jQuery
.bind( eventType [, eventData ], handler )
```

---

**Consideration 2:**

Also, as `value` given here is an anonymous function to pass to `bind()` method I'm almost sure this `bind()` method is from [wp-includes/js/customize-base.js](https://github.com/WordPress/WordPress/blob/44caec31bdc9cd0e65c6d433f22ca9e49e1a2683/wp-includes/js/customize-base.js)

```js
// storefront-footer-bar/assets/js/customizer.js

wp.customize( 'sfb_background_color', function( value ) {
        value.bind( function( to ) {
 	        $( '.sfb-footer-bar' ).css( 'background-color', to );
 	});
});
```

---

**Consideration 3:**

The `value` mentioned above can access `bind()`, `unbind()`, `setter()` and other methods from customize-base.js file

[wp-includes/js/customize-base.js#L272](https://github.com/WordPress/WordPress/blob/44caec31bdc9cd0e65c6d433f22ca9e49e1a2683/wp-includes/js/customize-base.js#L272)

```js
// wp-includes/js/customize-base.js#L272

api.Value = api.Class.extend(/** @lends wp.customize.Value.prototype */{
    // ...
        bind: function() {
            this.callbacks.add.apply( this.callbacks, arguments );
                return this;
        },
    // ...
});
```

---

**Test**
```js
// storefront-footer-bar/assets/js/customizer.js

( function( $ ) {
	wp.customize( 'sfb_background_color', function( value ) {

                // setter() method comes from customizer-base.js
		value.setter(function (data) {
			console.log(data)
		});

		value.bind( function( to ) {
			$( '.sfb-footer-bar' ).css( 'background-color', to );
		} );
	} );
        // ...
} )( jQuery );
```

**Result:**
![Screenshot from 2021-10-15 12-20-05](https://user-images.githubusercontent.com/744184/137513116-eb9bcc99-4826-446d-860c-e468cc799245.png)

---

IMO, the `bind()` method on this plugin is not a jQuery method. Let me know what you think about it.


Best,
Yeremi

**Comment by findingsimple** [comment]
Hi @yeremi thanks for the detailed investigation. 

> IMO, the bind() method on this plugin is not a jQuery method.

Ok, I think it was picked up by some automated checkers on our end and flagged as being deprecated, if everything is running smoothly with not deprecation warnings happy to close this one out based on your findings. We can always re-investigate
